use super::{SettingDefinition, definitions};

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SettingKey {
    AdminRemoteEnabled,
    AdminSessionIdleTimeout,
    AdminSessionAbsoluteTimeout,
    AdminLoginFailureWindow,
    AdminLoginMaxFailures,
    NetworkMaxConnections,
    NetworkRequestHeaderTimeout,
    NetworkRequestBodyIdleTimeout,
    NetworkTrustedProxyCidrs,
    ModelsAllowed,
    AffinityEnabled,
    AffinityTtl,
    AffinityWaitTimeout,
    LogsRequestEnabled,
    LogsRequestRetention,
    LogsRequestMaxRows,
    LogsHttpAccessMaxRows,
    LogsFileLevel,
    LogsFileRetention,
    LogsFileMaxTotalSize,
    LogsTelemetryQueueCapacity,
    LogsTelemetryQueueMaxBytes,
    OAuthRefreshScanInterval,
    OAuthRefreshLeadTime,
    OAuthCodexRateCard,
    UpstreamReadTimeout,
    UpstreamStrictSsrf,
    StreamPrecommitMaxBytes,
    StreamPrecommitMaxDuration,
    StreamPostcommitIdleTimeout,
    ShutdownRequestGracePeriod,
    ShutdownFinalizeTimeout,
    SchedulerOnRateLimited,
    SchedulerQueueTimeout,
    SchedulerMaxWaitingRequests,
    SchedulerFallbackOnRateLimit,
    RetryPrecommitTotalBudget,
}

impl SettingKey {
    pub const ALL: [Self; 37] = [
        Self::AdminRemoteEnabled,
        Self::AdminSessionIdleTimeout,
        Self::AdminSessionAbsoluteTimeout,
        Self::AdminLoginFailureWindow,
        Self::AdminLoginMaxFailures,
        Self::NetworkMaxConnections,
        Self::NetworkRequestHeaderTimeout,
        Self::NetworkRequestBodyIdleTimeout,
        Self::NetworkTrustedProxyCidrs,
        Self::ModelsAllowed,
        Self::AffinityEnabled,
        Self::AffinityTtl,
        Self::AffinityWaitTimeout,
        Self::LogsRequestEnabled,
        Self::LogsRequestRetention,
        Self::LogsRequestMaxRows,
        Self::LogsHttpAccessMaxRows,
        Self::LogsFileLevel,
        Self::LogsFileRetention,
        Self::LogsFileMaxTotalSize,
        Self::LogsTelemetryQueueCapacity,
        Self::LogsTelemetryQueueMaxBytes,
        Self::OAuthRefreshScanInterval,
        Self::OAuthRefreshLeadTime,
        Self::OAuthCodexRateCard,
        Self::UpstreamReadTimeout,
        Self::UpstreamStrictSsrf,
        Self::StreamPrecommitMaxBytes,
        Self::StreamPrecommitMaxDuration,
        Self::StreamPostcommitIdleTimeout,
        Self::ShutdownRequestGracePeriod,
        Self::ShutdownFinalizeTimeout,
        Self::SchedulerOnRateLimited,
        Self::SchedulerQueueTimeout,
        Self::SchedulerMaxWaitingRequests,
        Self::SchedulerFallbackOnRateLimit,
        Self::RetryPrecommitTotalBudget,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AdminRemoteEnabled => "admin.remote_enabled",
            Self::AdminSessionIdleTimeout => "admin.session.idle_timeout",
            Self::AdminSessionAbsoluteTimeout => "admin.session.absolute_timeout",
            Self::AdminLoginFailureWindow => "admin.login.failure_window",
            Self::AdminLoginMaxFailures => "admin.login.max_failures",
            Self::NetworkMaxConnections => "network.max_connections",
            Self::NetworkRequestHeaderTimeout => "network.request_header_timeout",
            Self::NetworkRequestBodyIdleTimeout => "network.request_body_idle_timeout",
            Self::NetworkTrustedProxyCidrs => "network.trusted_proxy_cidrs",
            Self::ModelsAllowed => "models.allowed",
            Self::AffinityEnabled => "affinity.enabled",
            Self::AffinityTtl => "affinity.ttl",
            Self::AffinityWaitTimeout => "affinity.wait_timeout",
            Self::LogsRequestEnabled => "logs.request.enabled",
            Self::LogsRequestRetention => "logs.request.retention",
            Self::LogsRequestMaxRows => "logs.request.max_rows",
            Self::LogsHttpAccessMaxRows => "logs.http_access.max_rows",
            Self::LogsFileLevel => "logs.file.level",
            Self::LogsFileRetention => "logs.file.retention",
            Self::LogsFileMaxTotalSize => "logs.file.max_total_size",
            Self::LogsTelemetryQueueCapacity => "logs.telemetry_queue_capacity",
            Self::LogsTelemetryQueueMaxBytes => "logs.telemetry_queue_max_bytes",
            Self::OAuthRefreshScanInterval => "oauth.refresh.scan_interval",
            Self::OAuthRefreshLeadTime => "oauth.refresh.lead_time",
            Self::OAuthCodexRateCard => "oauth.codex.rate_card",
            Self::UpstreamReadTimeout => "upstream.read_timeout",
            Self::UpstreamStrictSsrf => "upstream.strict_ssrf",
            Self::StreamPrecommitMaxBytes => "stream.precommit.max_bytes",
            Self::StreamPrecommitMaxDuration => "stream.precommit.max_duration",
            Self::StreamPostcommitIdleTimeout => "stream.postcommit.idle_timeout",
            Self::ShutdownRequestGracePeriod => "shutdown.request_grace_period",
            Self::ShutdownFinalizeTimeout => "shutdown.finalize_timeout",
            Self::SchedulerOnRateLimited => "scheduler.on_rate_limited",
            Self::SchedulerQueueTimeout => "scheduler.queue_timeout",
            Self::SchedulerMaxWaitingRequests => "scheduler.max_waiting_requests",
            Self::SchedulerFallbackOnRateLimit => "scheduler.fallback_on_rate_limit",
            Self::RetryPrecommitTotalBudget => "retry.precommit_total_budget",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|key| key.as_str() == value)
    }

    pub fn definition(self) -> SettingDefinition {
        definitions::definition(self)
    }
}
