use super::{SettingDefinition, definitions};

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SettingKey {
    AdminRemoteEnabled,
    AdminSessionIdleTimeout,
    AdminSessionAbsoluteTimeout,
    AdminLoginFailureWindow,
    AdminLoginMaxFailures,
    AffinitySoftEnabled,
    AffinitySoftMode,
    AffinitySoftTtl,
    AffinityHardTtl,
    AffinitySoftPreferWaitTimeout,
    AffinityFixedWaitTimeout,
    LogsRequestEnabled,
    LogsRequestRetention,
    LogsRequestMaxRows,
    LogsTelemetryQueueCapacity,
    UpstreamReadTimeout,
    StreamPrecommitMaxBytes,
    StreamPrecommitMaxDuration,
    StreamPostcommitIdleTimeout,
    SchedulerOnSaturated,
    SchedulerQueueTimeout,
    SchedulerMaxWaitingRequests,
    SchedulerFallbackOnSaturation,
    SchedulerAuxiliaryGlobalConcurrency,
    SchedulerAuxiliaryPerCredentialConcurrency,
    RetryMaxTotalAttempts,
    RetryMaxCredentialSwitches,
    RetryMaxSameCredentialRetries,
    RetryPrecommitTotalBudget,
    RetryBaseDelay,
    RetryMaxDelay,
    RetryJitterRatio,
    CooldownRateLimitFallback,
    CooldownModelUnsupported,
    CooldownPermissionDenied,
    CooldownTransientEndpoint,
    BreakerEndpointFailureThreshold,
    BreakerEndpointFailureWindow,
    BreakerEndpointOpenDuration,
    BreakerProxyFailureThreshold,
    BreakerProxyFailureWindow,
    BreakerProxyOpenDuration,
    BreakerHalfOpenMaxProbes,
}

impl SettingKey {
    pub const ALL: [Self; 43] = [
        Self::AdminRemoteEnabled,
        Self::AdminSessionIdleTimeout,
        Self::AdminSessionAbsoluteTimeout,
        Self::AdminLoginFailureWindow,
        Self::AdminLoginMaxFailures,
        Self::AffinitySoftEnabled,
        Self::AffinitySoftMode,
        Self::AffinitySoftTtl,
        Self::AffinityHardTtl,
        Self::AffinitySoftPreferWaitTimeout,
        Self::AffinityFixedWaitTimeout,
        Self::LogsRequestEnabled,
        Self::LogsRequestRetention,
        Self::LogsRequestMaxRows,
        Self::LogsTelemetryQueueCapacity,
        Self::UpstreamReadTimeout,
        Self::StreamPrecommitMaxBytes,
        Self::StreamPrecommitMaxDuration,
        Self::StreamPostcommitIdleTimeout,
        Self::SchedulerOnSaturated,
        Self::SchedulerQueueTimeout,
        Self::SchedulerMaxWaitingRequests,
        Self::SchedulerFallbackOnSaturation,
        Self::SchedulerAuxiliaryGlobalConcurrency,
        Self::SchedulerAuxiliaryPerCredentialConcurrency,
        Self::RetryMaxTotalAttempts,
        Self::RetryMaxCredentialSwitches,
        Self::RetryMaxSameCredentialRetries,
        Self::RetryPrecommitTotalBudget,
        Self::RetryBaseDelay,
        Self::RetryMaxDelay,
        Self::RetryJitterRatio,
        Self::CooldownRateLimitFallback,
        Self::CooldownModelUnsupported,
        Self::CooldownPermissionDenied,
        Self::CooldownTransientEndpoint,
        Self::BreakerEndpointFailureThreshold,
        Self::BreakerEndpointFailureWindow,
        Self::BreakerEndpointOpenDuration,
        Self::BreakerProxyFailureThreshold,
        Self::BreakerProxyFailureWindow,
        Self::BreakerProxyOpenDuration,
        Self::BreakerHalfOpenMaxProbes,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AdminRemoteEnabled => "admin.remote_enabled",
            Self::AdminSessionIdleTimeout => "admin.session.idle_timeout",
            Self::AdminSessionAbsoluteTimeout => "admin.session.absolute_timeout",
            Self::AdminLoginFailureWindow => "admin.login.failure_window",
            Self::AdminLoginMaxFailures => "admin.login.max_failures",
            Self::AffinitySoftEnabled => "affinity.soft.enabled",
            Self::AffinitySoftMode => "affinity.soft.mode",
            Self::AffinitySoftTtl => "affinity.soft.ttl",
            Self::AffinityHardTtl => "affinity.hard.ttl",
            Self::AffinitySoftPreferWaitTimeout => "affinity.soft.prefer_wait_timeout",
            Self::AffinityFixedWaitTimeout => "affinity.fixed_wait_timeout",
            Self::LogsRequestEnabled => "logs.request.enabled",
            Self::LogsRequestRetention => "logs.request.retention",
            Self::LogsRequestMaxRows => "logs.request.max_rows",
            Self::LogsTelemetryQueueCapacity => "logs.telemetry_queue_capacity",
            Self::UpstreamReadTimeout => "upstream.read_timeout",
            Self::StreamPrecommitMaxBytes => "stream.precommit.max_bytes",
            Self::StreamPrecommitMaxDuration => "stream.precommit.max_duration",
            Self::StreamPostcommitIdleTimeout => "stream.postcommit.idle_timeout",
            Self::SchedulerOnSaturated => "scheduler.on_saturated",
            Self::SchedulerQueueTimeout => "scheduler.queue_timeout",
            Self::SchedulerMaxWaitingRequests => "scheduler.max_waiting_requests",
            Self::SchedulerFallbackOnSaturation => "scheduler.fallback_on_saturation",
            Self::SchedulerAuxiliaryGlobalConcurrency => "scheduler.auxiliary_global_concurrency",
            Self::SchedulerAuxiliaryPerCredentialConcurrency => {
                "scheduler.auxiliary_per_credential_concurrency"
            }
            Self::RetryMaxTotalAttempts => "retry.max_total_attempts",
            Self::RetryMaxCredentialSwitches => "retry.max_credential_switches",
            Self::RetryMaxSameCredentialRetries => "retry.max_same_credential_retries",
            Self::RetryPrecommitTotalBudget => "retry.precommit_total_budget",
            Self::RetryBaseDelay => "retry.base_delay",
            Self::RetryMaxDelay => "retry.max_delay",
            Self::RetryJitterRatio => "retry.jitter_ratio",
            Self::CooldownRateLimitFallback => "cooldown.rate_limit_fallback",
            Self::CooldownModelUnsupported => "cooldown.model_unsupported",
            Self::CooldownPermissionDenied => "cooldown.permission_denied",
            Self::CooldownTransientEndpoint => "cooldown.transient_endpoint",
            Self::BreakerEndpointFailureThreshold => "breaker.endpoint.failure_threshold",
            Self::BreakerEndpointFailureWindow => "breaker.endpoint.failure_window",
            Self::BreakerEndpointOpenDuration => "breaker.endpoint.open_duration",
            Self::BreakerProxyFailureThreshold => "breaker.proxy.failure_threshold",
            Self::BreakerProxyFailureWindow => "breaker.proxy.failure_window",
            Self::BreakerProxyOpenDuration => "breaker.proxy.open_duration",
            Self::BreakerHalfOpenMaxProbes => "breaker.half_open_max_probes",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|key| key.as_str() == value)
    }

    pub const fn definition(self) -> SettingDefinition {
        definitions::definition(self)
    }
}
