use super::{SettingDefinition, definitions};

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SettingKey {
    AdminRemoteEnabled,
    AdminSessionIdleTimeout,
    AdminSessionAbsoluteTimeout,
    AdminLoginFailureWindow,
    AdminLoginMaxFailures,
    NetworkTrustedProxyCidrs,
    ModelsAllowed,
    AffinityEnabled,
    AffinityTtl,
    AffinityWaitTimeout,
    LogsRequestEnabled,
    LogsRequestRetention,
    LogsRequestMaxRows,
    LogsHttpAccessMaxRows,
    LogsHttpAccessMaxExchangeBytes,
    LogsFileLevel,
    LogsFileRetention,
    LogsFileMaxTotalSize,
    LogsTelemetryQueueCapacity,
    LogsTelemetryQueueMaxBytes,
    OAuthRefreshScanInterval,
    OAuthRefreshLeadTime,
    UpstreamReadTimeout,
    UpstreamStrictSsrf,
    StreamPrecommitMaxBytes,
    StreamPrecommitMaxDuration,
    StreamPostcommitIdleTimeout,
    ShutdownRequestGracePeriod,
    ShutdownFinalizeTimeout,
    SchedulerOnRateLimited,
    SchedulerQueueTimeout,
    SchedulerMaxWaitingRequests,
    SchedulerFallbackOnRateLimit,
    RetryMaxTotalAttempts,
    RetryMaxCredentialSwitches,
    RetryMaxSameCredentialRetries,
    RetryPrecommitTotalBudget,
    RetryBaseDelay,
    RetryMaxDelay,
    RetryJitterRatio,
    CooldownRateLimitFallback,
    CooldownModelUnsupported,
    CooldownPermissionDenied,
    CooldownTransientEndpoint,
    BreakerEndpointFailureThreshold,
    BreakerEndpointFailureWindow,
    BreakerEndpointOpenDuration,
    BreakerProxyFailureThreshold,
    BreakerProxyFailureWindow,
    BreakerProxyOpenDuration,
    BreakerHalfOpenMaxProbes,
}

impl SettingKey {
    pub const ALL: [Self; 51] = [
        Self::AdminRemoteEnabled,
        Self::AdminSessionIdleTimeout,
        Self::AdminSessionAbsoluteTimeout,
        Self::AdminLoginFailureWindow,
        Self::AdminLoginMaxFailures,
        Self::NetworkTrustedProxyCidrs,
        Self::ModelsAllowed,
        Self::AffinityEnabled,
        Self::AffinityTtl,
        Self::AffinityWaitTimeout,
        Self::LogsRequestEnabled,
        Self::LogsRequestRetention,
        Self::LogsRequestMaxRows,
        Self::LogsHttpAccessMaxRows,
        Self::LogsHttpAccessMaxExchangeBytes,
        Self::LogsFileLevel,
        Self::LogsFileRetention,
        Self::LogsFileMaxTotalSize,
        Self::LogsTelemetryQueueCapacity,
        Self::LogsTelemetryQueueMaxBytes,
        Self::OAuthRefreshScanInterval,
        Self::OAuthRefreshLeadTime,
        Self::UpstreamReadTimeout,
        Self::UpstreamStrictSsrf,
        Self::StreamPrecommitMaxBytes,
        Self::StreamPrecommitMaxDuration,
        Self::StreamPostcommitIdleTimeout,
        Self::ShutdownRequestGracePeriod,
        Self::ShutdownFinalizeTimeout,
        Self::SchedulerOnRateLimited,
        Self::SchedulerQueueTimeout,
        Self::SchedulerMaxWaitingRequests,
        Self::SchedulerFallbackOnRateLimit,
        Self::RetryMaxTotalAttempts,
        Self::RetryMaxCredentialSwitches,
        Self::RetryMaxSameCredentialRetries,
        Self::RetryPrecommitTotalBudget,
        Self::RetryBaseDelay,
        Self::RetryMaxDelay,
        Self::RetryJitterRatio,
        Self::CooldownRateLimitFallback,
        Self::CooldownModelUnsupported,
        Self::CooldownPermissionDenied,
        Self::CooldownTransientEndpoint,
        Self::BreakerEndpointFailureThreshold,
        Self::BreakerEndpointFailureWindow,
        Self::BreakerEndpointOpenDuration,
        Self::BreakerProxyFailureThreshold,
        Self::BreakerProxyFailureWindow,
        Self::BreakerProxyOpenDuration,
        Self::BreakerHalfOpenMaxProbes,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AdminRemoteEnabled => "admin.remote_enabled",
            Self::AdminSessionIdleTimeout => "admin.session.idle_timeout",
            Self::AdminSessionAbsoluteTimeout => "admin.session.absolute_timeout",
            Self::AdminLoginFailureWindow => "admin.login.failure_window",
            Self::AdminLoginMaxFailures => "admin.login.max_failures",
            Self::NetworkTrustedProxyCidrs => "network.trusted_proxy_cidrs",
            Self::ModelsAllowed => "models.allowed",
            Self::AffinityEnabled => "affinity.enabled",
            Self::AffinityTtl => "affinity.ttl",
            Self::AffinityWaitTimeout => "affinity.wait_timeout",
            Self::LogsRequestEnabled => "logs.request.enabled",
            Self::LogsRequestRetention => "logs.request.retention",
            Self::LogsRequestMaxRows => "logs.request.max_rows",
            Self::LogsHttpAccessMaxRows => "logs.http_access.max_rows",
            Self::LogsHttpAccessMaxExchangeBytes => "logs.http_access.max_exchange_bytes",
            Self::LogsFileLevel => "logs.file.level",
            Self::LogsFileRetention => "logs.file.retention",
            Self::LogsFileMaxTotalSize => "logs.file.max_total_size",
            Self::LogsTelemetryQueueCapacity => "logs.telemetry_queue_capacity",
            Self::LogsTelemetryQueueMaxBytes => "logs.telemetry_queue_max_bytes",
            Self::OAuthRefreshScanInterval => "oauth.refresh.scan_interval",
            Self::OAuthRefreshLeadTime => "oauth.refresh.lead_time",
            Self::UpstreamReadTimeout => "upstream.read_timeout",
            Self::UpstreamStrictSsrf => "upstream.strict_ssrf",
            Self::StreamPrecommitMaxBytes => "stream.precommit.max_bytes",
            Self::StreamPrecommitMaxDuration => "stream.precommit.max_duration",
            Self::StreamPostcommitIdleTimeout => "stream.postcommit.idle_timeout",
            Self::ShutdownRequestGracePeriod => "shutdown.request_grace_period",
            Self::ShutdownFinalizeTimeout => "shutdown.finalize_timeout",
            Self::SchedulerOnRateLimited => "scheduler.on_rate_limited",
            Self::SchedulerQueueTimeout => "scheduler.queue_timeout",
            Self::SchedulerMaxWaitingRequests => "scheduler.max_waiting_requests",
            Self::SchedulerFallbackOnRateLimit => "scheduler.fallback_on_rate_limit",
            Self::RetryMaxTotalAttempts => "retry.max_total_attempts",
            Self::RetryMaxCredentialSwitches => "retry.max_credential_switches",
            Self::RetryMaxSameCredentialRetries => "retry.max_same_credential_retries",
            Self::RetryPrecommitTotalBudget => "retry.precommit_total_budget",
            Self::RetryBaseDelay => "retry.base_delay",
            Self::RetryMaxDelay => "retry.max_delay",
            Self::RetryJitterRatio => "retry.jitter_ratio",
            Self::CooldownRateLimitFallback => "cooldown.rate_limit_fallback",
            Self::CooldownModelUnsupported => "cooldown.model_unsupported",
            Self::CooldownPermissionDenied => "cooldown.permission_denied",
            Self::CooldownTransientEndpoint => "cooldown.transient_endpoint",
            Self::BreakerEndpointFailureThreshold => "breaker.endpoint.failure_threshold",
            Self::BreakerEndpointFailureWindow => "breaker.endpoint.failure_window",
            Self::BreakerEndpointOpenDuration => "breaker.endpoint.open_duration",
            Self::BreakerProxyFailureThreshold => "breaker.proxy.failure_threshold",
            Self::BreakerProxyFailureWindow => "breaker.proxy.failure_window",
            Self::BreakerProxyOpenDuration => "breaker.proxy.open_duration",
            Self::BreakerHalfOpenMaxProbes => "breaker.half_open_max_probes",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|key| key.as_str() == value)
    }

    pub fn definition(self) -> SettingDefinition {
        definitions::definition(self)
    }
}
